### ISSUE TITLE
not able to archive the project 

### ISSUE THREAD

**Issue by ninadkambli17** [kewlbear/PythonPlayground#1]
/Python-iOS/Sources/Symbols/Symbols.m:27:9: 'Python.h' file not found

**Comment by kewlbear** [comment]
Fixed.  Please note that Xcode 12.4 have issues with archive/upload.  Use Xcode 12.5 beta 3.

**Comment by ninadkambli17** [comment]
tried with 12.5 beta 3.

getting following error

Invalid Swift Support. The file xxx/Frameworks/libssl.a, xxx.app/Frameworks/libbz2.a, xxxapp/Frameworks/liblzma.a, xxx.app/Frameworks/libpython3.8.a, xxx.app/Frameworks/libcrypto.a doesn’t have the correct file type for this location. Ensure you’re using the correct file, rebuild your app using the current public (GM) version of Xcode, and resubmit it. With error code STATE_ERROR.VALIDATION_ERROR.90432 for id 2874e9ce-736d-479f-8e82-c07e081b2b9c

**Comment by kewlbear** [comment]
Please make sure to update this project and dependencies.  By the way I'm looking for a solution for TestFlight crash.

**Comment by kewlbear** [comment]
> By the way I'm looking for a solution for TestFlight crash.

Done.

**Comment by ninadkambli17** [comment]
I archived using 12.5 beta 3 but got the following error while submitting the app
<img width="1168" alt="Screenshot 2021-04-23 at 11 54 23 PM" src="https://user-images.githubusercontent.com/23742346/115954833-b6ced480-a510-11eb-8393-47d48f9e97ae.png">


> > By the way I'm looking for a solution for TestFlight crash.
> 
> Done.
great !!!

**Comment by ninadkambli17** [comment]
App Store Connect Operation Error
ERROR ITMS-90432: "Invalid Swift Support. The file xxx.app/Frameworks/libssl.a, xxx.app/Frameworks/libbz2.a, xxx.app/Frameworks/liblzma.a, xxx.app/Frameworks/libpython3.8.a, xxx.app/Frameworks/libcrypto.a doesn’t have the correct file type for this location. Ensure you’re using the correct file, rebuild your app using the current public (GM) version of Xcode, and resubmit it."

and 

ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'xxxapp/Frameworks/libssl.a' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

with 12.4 xcode

**Comment by kewlbear** [comment]
> App Store Connect Operation Error
> ERROR ITMS-90432: "Invalid Swift Support. The file xxx.app/Frameworks/libssl.a, xxx.app/Frameworks/libbz2.a, xxx.app/Frameworks/liblzma.a, xxx.app/Frameworks/libpython3.8.a, xxx.app/Frameworks/libcrypto.a doesn’t have the correct file type for this location. Ensure you’re using the correct file, rebuild your app using the current public (GM) version of Xcode, and resubmit it."
> 
> and
> 
> ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'xxxapp/Frameworks/libssl.a' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
> 
> with 12.4 xcode

With 12.4 it's expected.  How about using 12.5 RC?

**Comment by ninadkambli17** [comment]
yes worked!!! with 12.5 RC @kewlbear thanks a lot for your support!!!
