### ISSUE TITLE
app crashing in the release scheme Py IncRef(pointer)

### ISSUE THREAD

**Issue by ninadkambli17** [kewlbear/PythonPlayground#2]
<img width="1658" alt="Screenshot 2021-05-05 at 2 43 00 PM" src="https://user-images.githubusercontent.com/23742346/117120043-76911100-adb0-11eb-9d0d-189227284c7f.png">
<img width="1680" alt="Screenshot 2021-05-05 at 2 45 35 PM" src="https://user-images.githubusercontent.com/23742346/117120312-cb348c00-adb0-11eb-8e56-f37524428bac.png">

**Comment by kewlbear** [comment]
It doesn't crash on my fresh checkout.  Are you using latest packages?

**Comment by ninadkambli17** [comment]
what is your xcode version. I am using it in 12.5. App store has also raised the same bug for 14.5 os version when given for review.

**Comment by kewlbear** [comment]
I'm also using Xcode 12.5 and iOS 14.5.  What's your settings for "Enable Bitcode" and "Strip Style"?

**Comment by ninadkambli17** [comment]
enable Bitcode is "YES" and "Strip Style"is "All symbols"

**Comment by kewlbear** [comment]
Okay. For release build you have to set strip style to debugging symbols.  For testflight/appstore you have to set enable bitcode to no.

**Comment by ninadkambli17** [comment]
I have set enable bitcode to no and strip style to for release build but still the app is crashing.

i invalidated the cache as well by going to file>swift packages> reset package cache and then I updated it by clicking file>swift packages> update to latest package version

**Comment by BhaveshSarwar** [comment]
Facing the same issue it get crash on import statement when running in release scheme

**Comment by BhaveshSarwar** [comment]
Even sample playground application is also crashing with same reason
Thread 1: EXC_BAD_ACCESS (code=1, address=0x0) on line 
        Py_IncRef(pointer)

**Comment by kewlbear** [comment]
> i invalidated the cache as well by going to file>swift packages> reset package cache and then I updated it by clicking file>swift packages> update to latest package version

Please update PythonSupport package by:

1. open project navigator (Command+1)
2. right-click (or control-click) PythonSupport package under Swift Package Dependencies
3. click Update Package

Update to latest package version doesn't seem to work when we specify dependencies with branches.

**Comment by ninadkambli17** [comment]
@BhaveshSarwar @kewlbear issue resolved. 

I did this.

 file>swift packages> update to latest package version.

**Comment by ninadkambli17** [comment]
> > i invalidated the cache as well by going to file>swift packages> reset package cache and then I updated it by clicking file>swift packages> update to latest package version
> 
> Please update PythonSupport package by:
> 
>     1. open project navigator (Command+1)
> 
>     2. right-click (or control-click) PythonSupport package under Swift Package Dependencies
> 
>     3. click Update Package
> 
> 
> Update to latest package version doesn't seem to work when we specify dependencies with branches.

@kewlbear you must be right. 

Connot trust file>swift packages> update to latest package version. 

But luckily worked for me after 4th attempt.

Thanks a lot for all your help and inputs!!!
