### ISSUE TITLE
Not able to import numpy, scipy and pandas

### ISSUE THREAD

**Issue by tabrez7311** [kewlbear/PythonPlayground#3]
```
PythonKit/Python.swift:674: Fatal error: 'try!' expression unexpectedly raised an error: Python exception: No module named 'numpy'
Traceback:
  File "/private/var/containers/Bundle/Application/8708A239-D782-4731-9D9B-263653B559AE/PythonTest.app/python/app.py", line 10, in <module>
    from analytics import etw
  File "/private/var/containers/Bundle/Application/8708A239-D782-4731-9D9B-263653B559AE/PythonTest.app/python/analytics/etw.py", line 12, in <module>
    import numpy
```

Hello @kewlbear , I wanted to execute my python code on iOS but I'm facing this issue. I'm a newbie can you please assist me on resolving this.

**Comment by kewlbear** [comment]
Those are not pure python. So you need to build native libraries for iOS.  But it's not easy to do.

**Comment by tabrez7311** [comment]
I have resolved the NumPy issue by integrating [Numpy-IOS](https://github.com/kewlbear/NumPy-iOS) . Can you please guide how I can create one. It would be a great help for me. Thanks

**Comment by kewlbear** [comment]
NumPy-iOS is built using kivy-ios recipe.  But it doesn't have recipes for scipy or pandas.  So you need to read build instructions for each package yourself.  And those instructions are not for iOS.  So you should understand how kiva-ios is working and adapt instructions to build recipes for kivy-ios.

Or you could investigate other open source projects for those packages.  Carnets and Pyto are promising ones.  But these projects are not easy to adapt either.

**Comment by tabrez7311** [comment]
Thanks for the guidance. However for now atleast I won't be doing it as currently I have eliminated this packages from python code. Made my python code work only based on Numpy. In future if needed will look into it with above mentioned ways.

P.S :- I had started making recipe for pandas but gave up half way through.
